---
## Defines the master API endpoint and the pod CIDR the network mesh will use
# This is the default used for calico
pod_cidr: "192.168.0.0/16"
## Will show as output from terraform "control_plane_ep"
k8s_endpoint: ""
## key to encrypt/decrypt certs on control plane
cert_key: ""

## Non root user on master node
# Defaults to cca-user
cluster_user: cca-user

## Choose network mesh for cluster, currently using calico
network_apply_command: "kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml"

# ansible_python_interpreter: "/usr/bin/python3"
