apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      web: ssl
  template:
    metadata:
      labels:
        web: ssl
    spec:
      volumes:
      - name: ssl-certs
        secret:
          secretName: ssl-certs
          items:
          - key: tls.crt
            path: certs/tls.crt
          - key: tls.key
            path: private/tls.key
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: ssl-webserver
        image: nginx:latest
        ports:
        - containerPort: 443
        volumeMounts:
## Mount certs from secret 
        - name: ssl-certs
          mountPath: /etc/ssl/
#        - name: nginx-config
#          mountPath: /etc/nginx/conf.d/ 
        env:
## fetch the pod IP for the nginx config
        - name: IPADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - /bin/bash
        - -c
        - >
          echo "server {
                  listen 443 http2 ssl;
                  listen [::]:443 http2 ssl;
                  server_name $IPADDRESS;
                  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
                  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
                  ssl_dhparam /etc/ssl/certs/dhparam.pem;
                }" >> /etc/nginx/conf.d/ssl.conf
        - nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-pod
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 443
  selector:
    web: ssl
  type: LoadBalancer
