- hosts: master
  become: yes
  tasks:
    - name: make sure docker daemon is Running
      systemd:
        name: docker
        state: started

    - name: initialize cluster
      ## add --create-cluster-endpoint {{ k8s_endpoint }} if you are using an IP different from the master default NIC
      command: kubeadm init --pod-network-cidr "{{ pod_cidr }}"

    - name: prepare kubectl for local user
      command: "{{ item }}"
      with_items:
       - mkdir -p /home/{{ master_user }}/.kube
       - cp -i /etc/kubernetes/admin.conf /home/{{ master_user }}/.kube/config
       - chown {{ master_user }}:{{ master_user }} /home/{{ master_user }}/.kube/config

    - name: deploy "{{ network }}"
      become: false
      become_user: "{{ master_user }}"
      command:
        cmd: "{{ network_apply_command }}"

    - name: create join command
      command: kubeadm token create --print-join-command
      register: join_command
      become: True

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- hosts: workers
  become: True
  tasks:
  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

- hosts: all
  become: True
  handlers:
  - name: docker status
    service: name=docker state=started
