- name: make sure docker daemon is Running
  hosts: all
  become: True
  tasks:
  - systemd:
      name: docker
      state: started

- hosts: kubeadm-test-master-01
  become: True
  tasks:
    - name: make sure kubelet is Running
      systemd:
        name: kubelet
        state: started

    - name: initialize cluster
      command: "kubeadm init --pod-network-cidr {{ pod_cidr }} --control-plane-endpoint {{ k8s_endpoint }} --certificate-key {{ cert_key }}"

    - name: prepare kubectl for local user
      command: "{{ item }}"
      with_items:
       - mkdir -p /home/{{ cluster_user }}/.kube
       - cp -i /etc/kubernetes/admin.conf /home/{{ cluster_user }}/.kube/config
       - chown {{ cluster_user }}:{{ cluster_user }} /home/{{ cluster_user }}/.kube/config

    - name: deploying CNI
      become: false
      command:
        cmd: "{{ network_apply_command }}"

    - name: create join command
      shell: "/bin/kubeadm token create --print-join-command"
      register: join_token

    - set_fact:
        join_command: "{{ join_token.stdout }}"

- hosts:
    - kubeadm-test-master-02
    - kubeadm-test-master-03
  become: True
  tasks:
    - name: join control plane
      command: "{{ hostvars['kubeadm-test-master-01']['join_command'] }} --control-plane --certificate-key {{ cert_key }}"
  when: 

- hosts: workers
  become: True
  tasks:
  - name: Join the node to cluster
    command: "{{ hostvars['kubeadm-test-master-01']['join_command'] }}"
