- hosts: master
  become: yes
  tasks:
    - name: make sure docker daemon is Running
      systemd:
        name: docker
        state: started

    - name: initialize cluster
      ## add --create-cluster-endpoint {{ k8s_endpoint }} if you are using an IP different from the master default NIC
      command: kubeadm init --pod-network-cidr "{{ pod_cidr }}"

    - name: prepare kubectl for local user
      command: "{{ item }}"
      with_items:
       - mkdir -p /home/{{ master_user }}/.kube
       - cp -i /etc/kubernetes/admin.conf /home/{{ master_user }}/.kube/config
       - chown {{ master_user }}:{{ master_user }} /home/{{ master_user }}/.kube/config

    - name: deploy "{{ network }}"
      become: false
      become_user: "{{ master_user }}"
      command:
        cmd: "{{ network_apply_command }}"
