---
- hosts: master
  tasks:
  - name: create join command
    command: kubeadm token create --print-join-command
    register: join_command
    become: True

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- hosts: workers
  become: True
  tasks:
  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

- hosts: all
  become: True
  handlers:
  - name: docker status
    service: name=docker state=started
