apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: blue
  template:
    metadata:
      labels:
        app: backend
        color: blue 
    spec:
      containers:
      - name: apikubectl c
        image: nginx:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - touch /usr/share/nginx/html/index.html
          - echo You have reached pod $MY_POD_NAME from the blue deployment > /usr/share/nginx/html/index.html
          - echo This pod lives on node $MY_NODE_NAME >> /usr/share/nginx/html/index.html

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: green
  template:
    metadata:
      labels:
        app: backend
        color: green 
    spec:
      containers:
      - name: api
        image: nginx:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
        - /bin/bash
        - echo 
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    ##Change the "color" value to blue or green to establish which version you want exposed
    color: blue
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  backend:
    serviceName: backend-service
    servicePort: 80
