apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: blue
  template:
    metadata:
      labels:
        app: backend
        color: blue 
    spec:
      volumes:
        - name: blue-index
          configMap:
            name: blue-index
            items:
              - key: index.html
                path: index.html
      containers:
      - name: api
        image: nginx:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: blue-index
            mountPath: /usr/share/nginx/html/
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: [ "sh", "-c"]
        args: 
        - echo Welcome to $MY_POD_NAME >> /usr/share/nginx/html/index.html

---

apiVersion: v1
data:
  index.html: "I am blue! "
kind: ConfigMap
metadata:
  name: blue-index
  labels:
    color: blue
    app: backend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: green
  template:
    metadata:
      labels:
        app: backend
        color: green 
    spec:
      volumes:
        - name: green-index
          configMap:
            name: green-index
            items:
              - key: index.html
                path: index.html
      containers:
      - name: api
        image: nginx:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: green-index
            mountPath: /usr/share/nginx/html/
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: [ "sh", "-c"]
        args: 
        - echo Welcome to $MY_POD_NAME >> /usr/share/nginx/html/index.html
        
---

apiVersion: v1
data:
  index.html: "I am green! "
kind: ConfigMap
metadata:
  name: green-index
  labels:
    color: green
    app: backend
    
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    ##Change the "color" value to blue or green to establish which version you want exposed
    color: blue
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  backend:
    serviceName: backend-service
    servicePort: 80
