apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: blue
  template:
    metadata:
      labels:
        app: backend
        color: blue 
    spec:
      volumes:
      - configMap:
          name: blue-cm
        name: blue-cm
      containers:
      - name: blue
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: blue-cm
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
data:
  index.html: |
    You have reached pod $MY_POD_NAME from the blue deployment.
    This pod lives on node $MY_NODE_NAME.
kind: ConfigMap
metadata:
  name: blue-cm
  labels:
    color: blue
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: green
  template:
    metadata:
      labels:
        app: backend
        color: green 
    spec:
      volumes:
      - configMap:
          name: green-cm
        name: green-cm
      containers:
      - name: green
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: green-cm
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
data:
  index.html: |
    You have reached pod $MY_POD_NAME from the green deployment.
    This pod lives on node $MY_NODE_NAME.
kind: ConfigMap
metadata:
  name: green-cm
  labels:
    color: green

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
    ##Change the "color" value to blue or green to establish which version you want exposed
    color: blue
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
