apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  serviceName: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: gcr.io/pwolthausen-dev1/debugger:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
