apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  replicas: 3
  selector:
    matchLabels:
      
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: 
        image: 
        ports:
        - containerPort: 
